# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    twig.extension.ep.epbundle.nomenclador_extension:
        class: EP\EPBundle\Twig\Extension\NomencladorExtension
        tags:
            - { name: twig.extension }
        arguments: 
        #["service", "doctrine.orm.entity_manager"]
            doctrine: "@doctrine"
